version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - go build -o bin/commit cmd/main.go

  run:
    desc: Run the app
    cmds:
      - task build
      - ./bin/commit {{ .CLI_ARGS }}
