version: "3"

tasks:
  run:
    desc: Run the app
    cmds:
      - GOGLAGS=-mod=mod go build -o bin/commit cmd/main.go && ./bin/commit

  build:
    desc: Build the app
    cmds:
      - GOGLAGS=-mod=mod go build -o bin/commit cmd/main.go
